# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
#      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarm:
      - 6
      - 7
    goarch:
      - amd64
      - arm
      - arm64
      - 386
brews:
   -
    name: gocloud
    tap:
      owner: ksrichard
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    download_strategy: CurlDownloadStrategy
    folder: Formula
    caveats: "Kick-start any cloud native project in your favourite programming language"
    homepage: "https://github.com/ksrichard/gocloud"
    description: "Kick-start any cloud native project in your favourite programming language"

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
